#include "ConstantDefinitions.h"
#include "stdint.h"

const uint8_t ONBOARDLED_REFRESH_RESOLUTION_MS = _ONBOARDLED_REFRESH_RESOLUTION_MS;
const uint8_t ONBOARDLED_BITS = _ONBOARDLED_BITS;
const uint8_t ONBOARDLED_COLOR_CHANGE_TIME_MS = _ONBOARDLED_COLOR_CHANGE_TIME_MS;
const uint32_t MUSIC_SAMPLE_FREQUENCY = _MUSIC_SAMPLE_FREQUENCY;
const uint8_t MUSIC_INTERPOLATION_RATIO = _MUSIC_INTERPOLATION_RATIO;
const uint32_t PIT_PERIOD = _PIT_PERIOD;

const uint8_t TPM_SHIFT_DIVIDER_CH0 = _TPM_SHIFT_DIVIDER_DEFAULT;
const uint32_t TPM_FREQUENCY_CH0 = _TPM_FREQUENCY_DEFAULT;
const uint8_t TPM_SHIFT_DIVIDER_CH1 = _TPM_SHIFT_DIVIDER_DEFAULT;
const uint32_t TPM_FREQUENCY_CH1 = _TPM_FREQUENCY_DEFAULT;
const uint8_t TPM_SHIFT_DIVIDER_CH2 = _TPM_SHIFT_DIVIDER_DEFAULT;
const uint32_t TPM_FREQUENCY_CH2 = _TPM_FREQUENCY_DEFAULT;

const uint16_t ChassisMaxPower = _CHASSIS_MAX_POWER;
